server:
  port: 9762

spring:
  datasource:
    druid:
      url: jdbc:mysql://152.136.84.40:3306/1812-1
      username: root
      password: PFcNiwOp
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: login-server
#spring cloud 服务提供者
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #链接注册中心的地址

#mapper扫描位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#Spring cloud提供者
